---
- name: templatize
  become: yes
  become_user: root
  with_items:
    - f: etc/nslcd.conf
      m: '0644'
    - f: etc/nsswitch.conf
      m: '0644'
    - f: etc/pam.d/ldap
      m: '0644'
  template: >-
    src={{item.f}}.j2
    dest=/{{item.f}}
    mode={{item.m}}
    
