---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"
    
- name: templatize
  become: yes
  become_user: root
  with_items:
    - f: etc/nslcd.conf
      m: '0600'
    - f: etc/nsswitch.conf
      m: '0600'
    - f: etc/pam.d/ldap
      m: '0600'
  template: >-
    src={{item.f}}.j2
    dest=/{{item.f}}
    mode={{item.m}}
    
